import {Routes, Route} from 'react-router-dom'
import {useState} from 'react'
import AppBar from './components/AppBar/AppBar.jsx'
import Dashboard from './pages/Dashboard.jsx'
import Analytics from './pages/Analytics.jsx'
import {trucks as initialtrucks} from './data/trucks.js'